site_name: Valley Vote Documentation
site_description: Documentation for the Valley Vote legislative data collection and analysis platform
repo_url: https://github.com/justinrm/valley-vote
repo_name: valley-vote

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Data Collection: user-guide/data-collection.md
    - Finance Scraping: user-guide/finance-scraping.md
    - Data Matching: user-guide/data-matching.md
    - Website Monitoring: user-guide/website-monitoring.md
  - API Reference:
    - Overview: api/index.md
    - Data Collection: api/data-collection.md
    - Finance Scraping: api/finance-scraping.md
    - Data Matching: api/data-matching.md
    - Utilities: api/utils.md
  - Data Schema: data-schema.md
  - Feature Engineering: feature-engineering.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_category_heading: true
            show_if_no_docstring: false
            heading_level: 2
            show_signature_annotations: true
            show_signature: true
            show_type_annotations: true
            show_docstring_attributes: true
            show_docstring_description: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_parameters: true
            show_docstring_raises: true
            show_docstring_returns: true
            show_docstring_type: true
            show_docstring_warns: true
            show_docstring_yields: true
            group_by_category: true
            show_submodules: true 